package clip.completion

object BashCompletion:

  def doc(app: String): String =
    s"""|# Completion script generated by clip
        |#
        |# The completion code supports nested commands ('verbs') each with their own set
        |# of named and positional parameters.
        |#
        |# The main entry point is the function __$${app}_handle_completion, which should be
        |# registered as the completion handler for the main command), e.g., via:
        |# `complete -F __$${app}_handle_completion $${app}`.
        |#
        |# This main entry point function walks through the command line words up to the
        |# current cursor position, keeping track of which positional parameter is being
        |# completed, and loading subcommand specifications as needed. The completion
        |# specifications are defined in functions named _$${app} (for the main command) and
        |# _$${app}_<subcommand> for subcommands, and can be extended by adding more such
        |# functions.
        |#
        |# Each such function needs to set up the following:
        |#
        |# - named: an array of named parameter specifications.
        |#
        |#   Each named parameter specification is a string of the form:
        |#   (--name:completer:help), where --name is the name of the parameter,
        |#   completer a completer type, and help a string which will be shown in the
        |#   completion list next to the parameter.
        |#
        |# - positional: an array of positional parameter specifications, where each
        |#   specification is a string of the form: (completer)
        |#
        |# - subcommands: an array of subcommand specifications, where each specification
        |#   is a string of the form: (subcommand:help), where subcommand is the name of
        |#   the subcommand, and help a string which will be shown in the completion list
        |#   next to the subcommand.
        |#
        |# The supported completer types are:
        |#
        |# - none: indicates that no completion should be provided for this parameter
        |#
        |# - default: use the default shell completion behavior (completes with file
        |#   names)
        |#
        |# - oneof(val1,val2,...): completes with one of the specified values
        |#
        |# - dynamic: invokes the main command with the environment variable
        |#   COMPLETE_LAST=1 set, and uses its output as the completion list
        |#
        |# - flag: similar to 'none', but indicates that the named parameter does not
        |#   take a value. This is used when walking the command line to distinguish
        |#   between arguments to named parameters and positional parameters. E.g.
        |#   if `--foo bar` is encountered, and --foo is of type 'flag', then 'bar' is
        |#   treated as a positional parameter, otherwise it would be treated as the
        |#   argument to --foo.
        |#
        |# shellcheck shell=bash
        |""".stripMargin

  def utils(app: String): String =
    s"""|# set BASH_COMP_DEBUG_FILE to a file path to enable debug logging of completions
        |__${app}_debug() {
        |    if [[ -n $${BASH_COMP_DEBUG_FILE-} ]]; then
        |        echo "$$*" >> "$${BASH_COMP_DEBUG_FILE}"
        |    fi
        |}
        |
        |# main completion handler
        |__${app}_handle_completion() {
        |    #shellcheck disable=SC2034
        |    local cur prev words cword # (cur and prev are unused here)
        |    _get_comp_words_by_ref -n = cur prev words cword
        |
        |    # current argument position (starts at 1, since word 0 is the command itself)
        |    local apos=1
        |    # current positional parameter index
        |    local ppos=0
        |    # subcommands processed so far
        |    local command_chain=""
        |
        |    # what to complete (this can be different from cur if completing an embedded
        |    # named parameter, e.g., --option=value)
        |    local partial=""
        |    # how to complete it
        |    local partial_completer="none"
        |
        |    # named parameter specifications
        |    # (--name:completer:help)
        |    # completer is one of "flag", "none", "default", or "dynamic"
        |    local named=()
        |    # positional parameter specifications
        |    # (completer)
        |    local positional=()
        |    # index of positional parameter that repeats indefinitely, -1 if none
        |    local repeat_pos=-1
        |    # subcommand specifications
        |    # (subcommand:help)
        |    local subcommands=()
        |
        |    __${app}_debug "starting completion for '$$COMP_LINE'"
        |
        |    # load initial command spec
        |    __${app}_debug "loading base command spec '_${app}'"
        |
        |    _${app}
        |
        |    # walk all arguments up to cword, keeping track of which positional
        |    # parameter we're at, and loading subcommand specs as we go
        |    local word=""
        |    __${app}_debug "walking words to find completer"
        |    while [[ $$apos -le $$cword ]]; do
        |        word="$${words[$$apos]}"
        |        partial="$$word"
        |
        |        case $$word in
        |            # ignore -- separator for completions
        |            --)
        |                apos=$$((apos + 1))
        |                ;;
        |            # a single '-' should be treated as a positional argument
        |            -)
        |                apos=$$((apos + 1))
        |                if [[ $$ppos -ne $$repeat_pos ]]; then
        |                    ppos=$$((ppos + 1))
        |                fi
        |                ;;
        |            # named option
        |            -*)
        |                local param="$$word"
        |                if [[ $$word == *=* ]]; then
        |                    # drop the '=value' part for matching the option name
        |                    param="$${word%%=*}"
        |                fi
        |
        |                apos=$$((apos + 1))
        |
        |                local spec=""
        |                for spec in "$${named[@]}"; do
        |                    IFS=':' read -r name completer help <<< "$$spec"
        |                    if [[ $$param == "$$name" ]]; then
        |                        partial_completer="$$completer"
        |                        if [[ $$word == *=* ]]; then
        |                            # completing the value after '='
        |                            partial="$${word#*=}"
        |                        # special completer "flag" means no argument
        |                        elif [[ $$completer != "flag" ]]; then
        |                            partial="$${words[$$apos]}"
        |                            apos=$$((apos + 1))
        |                        fi
        |                    fi
        |                done
        |                ;;
        |            *)
        |                if [[ $$ppos -lt $${#positional[@]} ]]; then
        |                    IFS=':' read -r completer <<< "$${positional[$$ppos]}"
        |                    partial_completer="$$completer"
        |                    if [[ $$ppos -ne $$repeat_pos ]]; then
        |                        ppos=$$((ppos + 1))
        |                    fi
        |                else
        |                    command_chain="$${command_chain}_$$word"
        |
        |                    if [[ $$ppos -ne $$repeat_pos ]]; then
        |                        ppos=$$((ppos + 1))
        |                    fi
        |
        |                    if declare -F "_${app}$$command_chain" >/dev/null; then
        |                        ppos=0
        |                        named=()
        |                        positional=()
        |                        subcommands=()
        |                        __${app}_debug "loading subcommand spec '_${app}$$command_chain'"
        |                        "_${app}$$command_chain"
        |                    else
        |                        partial_completer="none"
        |                    fi
        |                    true
        |                fi
        |                apos=$$((apos + 1))
        |                ;;
        |        esac
        |    done
        |
        |    # after walking all words, 'partial' holds the word to complete, and
        |    # 'partial_completer' holds how to complete it.
        |
        |    __${app}_debug "done walking words"
        |    __${app}_debug "partial: '$$partial'"
        |    __${app}_debug "partial_completer: '$$partial_completer'"
        |
        |    local tab=$$'\t'
        |    local longest=0
        |
        |    if [[ $$partial == -* ]]; then
        |        __${app}_debug "completing named parameter"
        |        COMPREPLY=()
        |        local spec=""
        |        for spec in "$${named[@]}"; do
        |            if [[ $$spec == "$$partial"* ]]; then
        |                IFS=':' read -r name completer help <<< "$$spec"
        |                COMPREPLY+=("$$name$$tab$$help")
        |                if (( $${#name} > longest )); then
        |                    longest=$${#name}
        |                fi
        |            fi
        |        done
        |    elif [[ $$ppos -eq $${#positional[@]}+1 ]]; then
        |        __${app}_debug "completing subcommand"
        |        COMPREPLY=()
        |        local cmd=""
        |        for cmd in "$${subcommands[@]}"; do
        |            if [[ $$cmd == "$$partial"* ]]; then
        |                IFS=':' read -r name help <<< "$$cmd"
        |                COMPREPLY+=("$$name$$tab$$help")
        |                if (( $${#name} > longest )); then
        |                    longest=$${#name}
        |                fi
        |            fi
        |        done
        |    else
        |        __${app}_debug "completing value"
        |        case $$partial_completer in
        |            none)
        |                COMPREPLY=()
        |                ;;
        |            default)
        |                compopt -o default
        |                ;;
        |            oneof\\(*\\))
        |                local alts="$${partial_completer#oneof(}"
        |                alts="$${alts%)}" # remove trailing ')'
        |                IFS=',' read -r -a options <<< "$$alts"
        |                COMPREPLY=()
        |                local opt=""
        |                for opt in "$${options[@]}"; do
        |                    if [[ $$opt == "$$partial"* ]]; then
        |                        COMPREPLY+=("$$opt")
        |                        if (( $${#opt} > longest )); then
        |                            longest=$${#opt}
        |                        fi
        |                    fi
        |                done
        |                ;;
        |            dynamic)
        |                # shellcheck disable=SC2207
        |                COMPREPLY=( $$(COMPLETE_LAST=1 $$COMP_LINE 2> /dev/null ) )
        |                ;;
        |            *)
        |                COMPREPLY=()
        |                ;;
        |        esac
        |
        |    fi
        |
        |    local i
        |    for i in $${!COMPREPLY[*]}; do
        |        __${app}_debug "COMPREPLY[$$i]: '$${COMPREPLY[i]}'"
        |    done
        |
        |    # if there's only one completion, remove any trailing help text
        |    if [[ $${#COMPREPLY[@]} -eq 1 ]]; then
        |        COMPREPLY=("$${COMPREPLY[0]%%$$tab*}")
        |        # don't emit a space after '='
        |        [[ "$${COMPREPLY[0]}" == *= ]] && compopt -o nospace
        |    else
        |        __${app}_format_replies "$$longest"
        |    fi
        |
        |    for i in $${!COMPREPLY[*]}; do
        |        __${app}_debug "final COMPREPLY[$$i]: '$${COMPREPLY[i]}'"
        |    done
        |    __${app}_debug ""
        |}
        |
        |__${app}_format_replies() {
        |    local tab=$$'\t'
        |    local comp desc maxdesclength
        |    local longest=$$1
        |
        |    local i ci
        |    for ci in $${!COMPREPLY[*]}; do
        |        comp=$${COMPREPLY[ci]}
        |        # properly format the description string which follows a tab character if there is one
        |        if [[ "$$comp" == *$$tab* ]]; then
        |            desc=$${comp#*$$tab}
        |            comp=$${comp%%$$tab*}
        |
        |            # $$COLUMNS stores the current shell width.
        |            # remove an extra 4 because we add 2 spaces and 2 parentheses.
        |            maxdesclength=$$(( COLUMNS - longest - 4 ))
        |
        |            # make sure we can fit a description of at least 8 characters
        |            # if we are to align the descriptions.
        |            if ((maxdesclength > 8)); then
        |                # Add the proper number of spaces to align the descriptions
        |                for ((i = $${#comp} ; i < longest ; i++)); do
        |                    comp+=" "
        |                done
        |            else
        |                # don't pad the descriptions so we can fit more text after the completion
        |                maxdesclength=$$(( COLUMNS - $${#comp} - 4 ))
        |            fi
        |
        |            # if there is enough space for any description text,
        |            # truncate the descriptions that are too long for the shell width
        |            if ((maxdesclength > 0)); then
        |                if (($${#desc} > maxdesclength)); then
        |                    desc=$${desc:0:$$(( maxdesclength - 1 ))}
        |                    desc+="…"
        |                fi
        |                comp+="  ($$desc)"
        |            fi
        |            COMPREPLY[ci]=$$comp
        |        fi
        |    done
        |}
        |""".stripMargin

  def specs(
      chain: Seq[String],
      params: Seq[ParamInfo],
      subcommands: Seq[SubcommandInfo]
  ): String =
    val b = new StringBuilder
    for cmd <- chain do b ++= s"_$cmd"
    b ++= "() {\n"

    var ppos = 0
    for param <- params do
      val completerStr =
        if param.isFlag then "flag"
        else
          param.completer match
            case Completer.Empty        => "none"
            case Completer.Default      => "default"
            case Completer.OneOf(words) => s"oneof(${words.mkString(",")})"
            case Completer.Dynamic(_)   => "dynamic"

      if param.isNamed then
        for name <- param.names do
          b ++= s"""  named+=("$name:$completerStr:${param.help}")\n"""
      else
        b ++= s"""  positional+=("$completerStr")\n"""
        if param.repeats then b ++= s"""  repeat_pos=$ppos\n"""
        ppos += 1
    end for

    for subcmd <- subcommands do
      b ++= s"""  subcommands+=("${subcmd.name}:${subcmd.help}")\n"""
    end for

    b ++= "}\n"
    b.result()

  def hook(app: String, names: Seq[String]): String =
    s"complete -F __${app}_handle_completion ${names.mkString(" ")}"
