import utest.*

object DerivationTest extends TestSuite:

  // run the following to see the command code generated by the macro:
  //
  //   println(scala.compiletime.codeOf(clip.derivation.commandFor(Container)))
  //
  // then recompile and run tests `mill clip.test DerivationTest`

  def testInvoke(cmd: clip.dispatch.Command[Any, ?], args: Iterable[String]) =
    clip.dispatch.invokeRaw(cmd, (), args)._2

  val tests = Tests:
    test("basic"):
      object Container:
        @clip.command()
        def foo(): Int = 2

        def bar(bar: String): Unit = ()

        val cmds = clip.derivation.subcommandsFor(Container)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      assert(
        testInvoke(Container.cmds.head, List()) ==
        clip.dispatch.InvocationResult.Success(2)
      )

    test("default"):
      object Container:
        @clip.command()
        def foo(x: Int = 10): Int = x + 5

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      val result1 = testInvoke(Container.cmds.head, List())
      assert(result1 == clip.dispatch.InvocationResult.Success(15))

      val result2 = testInvoke(Container.cmds.head, List("--x=20"))
      assert(result2 == clip.dispatch.InvocationResult.Success(25))

      val result3 = testInvoke(Container.cmds.head, List("--x", "20"))
      assert(result3 == clip.dispatch.InvocationResult.Success(25))

    test("arg annot"):
      object Container:
        @clip.command()
        def foo(@clip.arg("--x-value") x: Int): Int = x * 2

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      val result = testInvoke(Container.cmds.head, List("--x-value", "3"))
      assert(result == clip.dispatch.InvocationResult.Success(6))

    test("aliases"):
      object Container:
        @clip.command()
        def foo(@clip.arg("--x-value", aliases = Seq("-x", "-y")) x: Int): Int = x * 2

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      assert(
        testInvoke(Container.cmds.head, List("--x-value", "3")) ==
        clip.dispatch.InvocationResult.Success(6)
      )
      assert(
        testInvoke(Container.cmds.head, List("-x", "4")) ==
        clip.dispatch.InvocationResult.Success(8)
      )
      assert(
        testInvoke(Container.cmds.head, List("-y", "5")) ==
        clip.dispatch.InvocationResult.Success(10)
      )

    test("repeated"):
      object Container:
        @clip.command()
        def foo(@clip.arg("--x-value", repeats = true) x: Seq[Int]): Int = x.sum

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      val result = testInvoke(
        Container.cmds.head,
        List("--x-value", "3", "--x-value", "4", "--x-value", "5")
      )
      assert(result == clip.dispatch.InvocationResult.Success(12))

    test("repeated map"):
      object Container:
        @clip.command()
        def foo(@clip.arg("--x-value", repeats = true) x: Map[String, Int]) = x

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      val result = testInvoke(
        Container.cmds.head,
        List("--x-value", "a=3", "--x-value", "b=4", "--x-value", "a=5")
      )
      assert(result == clip.dispatch.InvocationResult.Success(Map("a" -> 5, "b" -> 4)))

    test("context"):
      object Container:
        class Ctx(val x: Int)

        @clip.command()
        def foo(@clip.context() c: Ctx, y: Int): Int = c.x + y

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmds.length == 1)
      assert(Container.cmds.head.name == "foo")

      val result = clip.dispatch.invokeRaw(
        Container.cmds.head,
        Container.Ctx(10),
        List("5")
      )

      assert(result._2 == clip.dispatch.InvocationResult.Success(15))

    test("group"):
      object Container:
        @clip.group()
        def foo(): Int = 42

        val cmd = clip.derivation.commandFor(this)

      assert(Container.cmd.name == "foo")
      assert(Container.cmd.terminal == false)
      assert(Container.cmd.listChildren().isEmpty)

      assert(
        testInvoke(Container.cmd, List()) ==
        clip.dispatch.InvocationResult.MissingCommand()
      )

    test("group2"):
      object Container:
        @clip.group()
        def foo(x: Int = 42): Int = x

        @clip.command()
        def bar(@clip.context x: Int): Int = x + 1

        @clip.command()
        def baz(@clip.context x: Int): Int = x + 2

        val cmd = clip.derivation.commandFor(this)

      assert(Container.cmd.name == "foo")
      assert(Container.cmd.terminal == false)
      assert(Container.cmd.listChildren().nonEmpty)
      assert(Container.cmd.listChildren().map(_.name).toSet == Set("bar", "baz"))

      assert(
        testInvoke(Container.cmd, List()) ==
        clip.dispatch.InvocationResult.MissingCommand()
      )
      assert(
        testInvoke(Container.cmd, List("bar")) ==
        clip.dispatch.InvocationResult.Success(43)
      )
      assert(
        testInvoke(Container.cmd, List("baz")) ==
        clip.dispatch.InvocationResult.Success(44)
      )
      assert(
        testInvoke(Container.cmd, List("other")) ==
        clip.dispatch.InvocationResult.UnknownCommand("other")
      )

      assert(
        testInvoke(Container.cmd, List("--x", "5", "bar")) ==
        clip.dispatch.InvocationResult.Success(6)
      )

    test("group3"):
      object Container:
        @clip.group(subcommands = Seq(
          SubcommandGroup.cmd,
        ) ++ Subcommands.cmds)
        def top(x: Int = 42): Int = x

        @clip.command()
        def topCmd(@clip.context x: Int): Int = x + 1

        val cmd = clip.derivation.commandFor(this)

      object SubcommandGroup:
        @clip.group()
        def sub(@clip.context() y: Int = 100): String = y.toString

        @clip.command()
        def subCmd(@clip.context y: String): String = y

        val cmd = clip.derivation.commandFor(this)

      object Subcommands:
        @clip.command()
        def topCmd2(@clip.context x: Int): Int = x + 10

        @clip.command()
        def topCmd3(@clip.context x: Int): Int = x + 20

        val cmds = clip.derivation.subcommandsFor(this)

      assert(Container.cmd.name == "top")
      assert(Container.cmd.listChildren().map(_.name).toSet ==
        Set("top-cmd", "top-cmd2", "top-cmd3", "sub")
      )
      assert(
        Container.cmd.getChild("sub").get.listChildren().map(_.name) == List("sub-cmd")
      )

      assert(
        testInvoke(Container.cmd, List("top-cmd2")) ==
        clip.dispatch.InvocationResult.Success(52)
      )
    test("custom arg reader"):
      assert(
        testInvoke(
          CustomArgReaderContainer.cmd,
          List("4")
        ) ==
        clip.dispatch.InvocationResult.Success(9)
      )
    test("custom arg api"):
      object Container:
        @clip.command()
        def foo(
          @clip.arg("x") x: Int,
          @CustomArgApi.arg("y") y: Int
        ) = x + y
        val cmd = clip.derivation.commandFor(this)

      assert(
        summon[CustomArgApi.Reader[Int]].read("3") == clip.derivation.ReadResult.Success(6)
      )
      assert(
        testInvoke(
          Container.cmd,
          List("3", "4")
        ) ==
        clip.dispatch.InvocationResult.Success(11)
      )

// for some reason we can't put an object containing a `given` inside a test
object CustomArgReaderContainer:
  given clip.derivation.default.Reader[Int] with
    def read(arg: String) =
      clip.derivation.ReadResult.Success(arg.toInt * 2)
    def typeName = "<double-int>"

  @clip.command()
  def foo(x: Int): Int = x + 1

  val cmd = clip.derivation.commandFor(this)

object CustomArgApi extends clip.derivation.Api:
  given Reader[Int] with
    def read(arg: String) =
      clip.derivation.ReadResult.Success(arg.toInt * 2)
    def typeName = "<double-int>"

