#!/bin/bash
set -o errexit

# update readme
./mill readme

# run tests

# comptest tests are time-sensitive and may fail under heavy load, so we run
# tests separately
# TODO: instead of enumerating all tests, find a way to all except comptest
./mill readers.__.test
./mill clip.__.test
./mill nativeexamples.__.test
./mill examples.__.test
./mill comptest.__.test
